/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author kylea
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public static void getMensaje(String msj){
        JOptionPane.showMessageDialog(null, msj);
    }
    
    public void escucharItems(ActionListener manejador){
        this.itemNew.addActionListener(manejador);
        this.itemEditDelete.addActionListener(manejador);
        this.itemList.addActionListener(manejador);
        this.itemPayment.addActionListener(manejador);
        this.itemExit.addActionListener(manejador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNew = new javax.swing.JMenuItem();
        itemPayment = new javax.swing.JMenuItem();
        itemList = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemEditDelete = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo 1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg3.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 380));

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));

        jMenu1.setBackground(new java.awt.Color(255, 51, 51));
        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("New");

        itemNew.setText("New Member");
        jMenu1.add(itemNew);

        itemPayment.setText("Payment");
        jMenu1.add(itemPayment);

        itemList.setText("List of Member");
        jMenu1.add(itemList);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 51, 51));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Edit");

        itemEditDelete.setText("Edit & Delete Member");
        jMenu2.add(itemEditDelete);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 51, 51));
        jMenu3.setForeground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("Option");

        itemExit.setText("Exit");
        jMenu3.add(itemExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemEditDelete;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemList;
    private javax.swing.JMenuItem itemNew;
    private javax.swing.JMenuItem itemPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
