/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author kylea
 */
public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
    }

    public void escuchar(ActionListener manejador) {
        this.btCheckIn.addActionListener(manejador);
        this.btSalir.addActionListener(manejador);
    }

    public Cliente getNewMember() {
        int id = Integer.parseInt(txtID.getText());
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        int telefono = Integer.parseInt(txtTelefono.getText());
        String comboCategory = (String) cBoxCategory.getSelectedItem();
        String comboPlan = (String) cBoxPayment.getSelectedItem();
        double altura = Double.parseDouble(txtHeight.getText());
        double peso = Double.parseDouble(txtWeight.getText());
        
        return new Cliente(id, nombre, apellido, edad, telefono, comboCategory, comboPlan, altura, peso);
    }

    public void cargarCombo(String[] listaOperaciones) {
        String[] membresias = {"Membresía Básica", "Membresía Estándar", "Membresía Premium", "Membresía Estudiantil"};
        String[] planesPago = {"Pago Mensual", "Pago Anual", "Pago Trimestral", "Pago Semestral", "Pago por día"};
        this.cBoxCategory.setModel(new DefaultComboBoxModel<>(membresias));
        this.cBoxPayment.setModel(new DefaultComboBoxModel<>(planesPago));
    }

    public String devolverCombo() {
        return this.cBoxCategory.getSelectedItem().toString();
    }

    public String devolverCombo2() {
        return this.cBoxPayment.getSelectedItem().toString();
    }

    public void limpiar() {
        this.txtNombre.setText("Ingrese su nombre");
        this.txtApellido.setText("Ingrese su apellido");
         this.txtID.setText("Ingrese su ID");
        this.txtEdad.setText("Ingrese su edad");
        this.txtTelefono.setText("0000-0000");
        this.txtHeight.setText("Ingrese su altura");
        this.txtWeight.setText("Ingrese su peso");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSalir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        cBoxCategory = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        cBoxPayment = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        btCheckIn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalir.setBackground(new java.awt.Color(51, 51, 51));
        btSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btSalir.setText("X");
        btSalir.setBorder(null);
        btSalir.setFocusPainted(false);
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSalirMouseExited(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 30, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("New Member");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg3.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Personal Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 20));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 10));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("Ingrese su apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 20));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, 10));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtID.setForeground(new java.awt.Color(204, 204, 204));
        txtID.setText("Ingrese su ID");
        txtID.setBorder(null);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 20));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 220, 10));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Age");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(204, 204, 204));
        txtEdad.setText("Ingrese su edad");
        txtEdad.setBorder(null);
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEdadMouseClicked(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, 20));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 220, 10));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 10, 310));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Membership Category");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 10));

        cBoxCategory.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        cBoxCategory.setForeground(new java.awt.Color(51, 51, 51));
        cBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Membresía Básica", "Membresía Estándar", "Membresía Premium", "Membresía Estudiantil" }));
        jPanel1.add(cBoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, 20));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Payment Plan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 200, 10));

        cBoxPayment.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        cBoxPayment.setForeground(new java.awt.Color(51, 51, 51));
        cBoxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago Mensual", "Pago Anual", "Pago Trimestral", "Pago Semestral", "Pago por día" }));
        jPanel1.add(cBoxPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, 20));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Height");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        txtHeight.setBackground(new java.awt.Color(255, 255, 255));
        txtHeight.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(204, 204, 204));
        txtHeight.setText("Ingrese su altura");
        txtHeight.setBorder(null);
        txtHeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHeightMouseClicked(evt);
            }
        });
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 200, 20));

        jSeparator9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Weight");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        txtWeight.setBackground(new java.awt.Color(255, 255, 255));
        txtWeight.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(204, 204, 204));
        txtWeight.setText("Ingrese su peso");
        txtWeight.setBorder(null);
        txtWeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWeightMouseClicked(evt);
            }
        });
        jPanel1.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 200, 20));

        jSeparator10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 200, 10));

        btCheckIn.setBackground(new java.awt.Color(255, 51, 51));
        btCheckIn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btCheckIn.setForeground(new java.awt.Color(51, 51, 51));
        btCheckIn.setText("Check In");
        btCheckIn.setBorder(null);
        btCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCheckInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCheckInMouseExited(evt);
            }
        });
        jPanel1.add(btCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 110, 40));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Phone Number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("0000-0000");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 240, 20));

        jSeparator11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCheckInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCheckInMouseEntered
        btCheckIn.setBackground(Color.DARK_GRAY);
        btCheckIn.setForeground(new java.awt.Color(222, 222, 222));
    }//GEN-LAST:event_btCheckInMouseEntered

    private void btCheckInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCheckInMouseExited
        btCheckIn.setBackground(new java.awt.Color(255, 51, 51));
        btCheckIn.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btCheckInMouseExited

    private void btSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseEntered
        btSalir.setBackground(new java.awt.Color(255, 51, 51));
        btSalir.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btSalirMouseEntered

    private void btSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseExited
        btSalir.setBackground(Color.DARK_GRAY);
        btSalir.setForeground(new java.awt.Color(222, 222, 222));
    }//GEN-LAST:event_btSalirMouseExited

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        if (txtNombre.getText().equals("Ingrese su nombre")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.DARK_GRAY);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese su apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
        if (txtEdad.getText().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.LIGHT_GRAY);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("0000-0000");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        if (txtHeight.getText().isEmpty()) {
            txtHeight.setText("Ingrese su altura");
            txtHeight.setForeground(Color.LIGHT_GRAY);
        }
        if (txtWeight.getText().isEmpty()) {
            txtWeight.setText("Ingrese su peso");
            txtWeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        if (txtApellido.getText().equals("Ingrese su apellido")) {
            txtApellido.setText("");
            txtApellido.setForeground(Color.DARK_GRAY);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
        if (txtEdad.getText().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.LIGHT_GRAY);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("0000-0000");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        if (txtHeight.getText().isEmpty()) {
            txtHeight.setText("Ingrese su altura");
            txtHeight.setForeground(Color.LIGHT_GRAY);
        }
        if (txtWeight.getText().isEmpty()) {
            txtWeight.setText("Ingrese su peso");
            txtWeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        if (txtID.getText().equals("Ingrese su ID")) {
            txtID.setText("");
            txtID.setForeground(Color.DARK_GRAY);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese su apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (txtEdad.getText().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.LIGHT_GRAY);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("0000-0000");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        if (txtHeight.getText().isEmpty()) {
            txtHeight.setText("Ingrese su altura");
            txtHeight.setForeground(Color.LIGHT_GRAY);
        }
        if (txtWeight.getText().isEmpty()) {
            txtWeight.setText("Ingrese su peso");
            txtWeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtIDMouseClicked

    private void txtEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMouseClicked
        if (txtEdad.getText().equals("Ingrese su edad")) {
            txtEdad.setText("");
            txtEdad.setForeground(Color.DARK_GRAY);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese su apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("0000-0000");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        if (txtHeight.getText().isEmpty()) {
            txtHeight.setText("Ingrese su altura");
            txtHeight.setForeground(Color.LIGHT_GRAY);
        }
        if (txtWeight.getText().isEmpty()) {
            txtWeight.setText("Ingrese su peso");
            txtWeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtEdadMouseClicked

    private void txtHeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHeightMouseClicked
        if (txtHeight.getText().equals("Ingrese su altura")) {
            txtHeight.setText("");
            txtHeight.setForeground(Color.DARK_GRAY);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese su apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
        if (txtEdad.getText().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.LIGHT_GRAY);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("0000-0000");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        if (txtWeight.getText().isEmpty()) {
            txtWeight.setText("Ingrese su peso");
            txtWeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtHeightMouseClicked

    private void txtWeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWeightMouseClicked
        if (txtWeight.getText().equals("Ingrese su peso")) {
            txtWeight.setText("");
            txtWeight.setForeground(Color.DARK_GRAY);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese su apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
        if (txtEdad.getText().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.LIGHT_GRAY);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("0000-0000");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        if (txtHeight.getText().isEmpty()) {
            txtHeight.setText("Ingrese su altura");
            txtHeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtWeightMouseClicked

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
       if (txtTelefono.getText().equals("0000-0000")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.DARK_GRAY);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese su apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
        if (txtEdad.getText().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.LIGHT_GRAY);
        }
        if (txtHeight.getText().isEmpty()) {
            txtHeight.setText("Ingrese su altura");
            txtHeight.setForeground(Color.LIGHT_GRAY);
        }
        if (txtWeight.getText().isEmpty()) {
            txtWeight.setText("Ingrese su peso");
            txtWeight.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtTelefonoMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCheckIn;
    private javax.swing.JButton btSalir;
    private javax.swing.JComboBox<String> cBoxCategory;
    private javax.swing.JComboBox<String> cBoxPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
