/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.User;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author kylea
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    public void escuchar(ActionListener manejador){
        this.btIngresar.addActionListener(manejador);
        this.btSalir.addActionListener(manejador);
    }
    
    public User getUserData(){
        int idUser= Integer.parseInt(txtID.getText());
        String password= new String(fieldPass.getPassword());
        
        User u = new User(idUser, password);
        u.setIdUser(idUser);
        u.setPassword(password);
        
        return u;
        
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fieldPass = new javax.swing.JPasswordField();
        btSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btIngresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 190));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Toro Loco GYM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("CONTRASEÑA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg4.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 370));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel4.setText("INICIAR SESION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        txtID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(204, 204, 204));
        txtID.setText("Ingrese su ID");
        txtID.setBorder(null);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 210, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, -1));

        fieldPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldPass.setForeground(new java.awt.Color(204, 204, 204));
        fieldPass.setText("********");
        fieldPass.setBorder(null);
        fieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPassMouseClicked(evt);
            }
        });
        jPanel1.add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 200, -1));

        btSalir.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btSalir.setForeground(new java.awt.Color(51, 51, 51));
        btSalir.setText("X");
        btSalir.setBorder(null);
        btSalir.setFocusPainted(false);
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSalirMouseExited(evt);
            }
        });
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btIngresar.setBackground(new java.awt.Color(255, 51, 51));
        btIngresar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btIngresar.setForeground(new java.awt.Color(51, 51, 51));
        btIngresar.setText("INGRESAR");
        btIngresar.setBorder(null);
        btIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btIngresarMouseExited(evt);
            }
        });
        jPanel1.add(btIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 120, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 2, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("¿Olvidó su contraseña?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIngresarMouseEntered
        btIngresar.setBackground(Color.DARK_GRAY);
        btIngresar.setForeground(new java.awt.Color(222, 222, 222));
    }//GEN-LAST:event_btIngresarMouseEntered

    private void btIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIngresarMouseExited
        btIngresar.setBackground(new java.awt.Color(255, 51, 51));
        btIngresar.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btIngresarMouseExited

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        if (txtID.getText().equals("Ingrese su ID")) {
            txtID.setText(""); 
            txtID.setForeground(Color.DARK_GRAY);
        }
        if (String.valueOf(fieldPass.getPassword()).isEmpty()) {
            fieldPass.setText("********");
            fieldPass.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtIDMouseClicked

    private void fieldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPassMouseClicked
        if (String.valueOf(fieldPass.getPassword()).equals("********")) {
            fieldPass.setText("");
            fieldPass.setForeground(Color.DARK_GRAY);
        }
        if (txtID.getText().isEmpty()) {
            txtID.setText("Ingrese su ID");
            txtID.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_fieldPassMouseClicked

    private void btSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseEntered
         btSalir.setBackground(Color.DARK_GRAY);
        btSalir.setForeground(new java.awt.Color(222, 222, 222));
    }//GEN-LAST:event_btSalirMouseEntered

    private void btSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseExited
       btSalir.setBackground(Color.WHITE);
        btSalir.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btSalirMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton btSalir;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
